### ISSUE TITLE
Navigation issues when using the `nuxt-link` component

### ISSUE THREAD

**Issue by delapuente** [qiskit-community/community.qiskit.org#69]
It would be convenient to use `nuxt-link` in order to provide JavaScript smooth scrolling and progressive enhancement to a SPA but there are problems while navigating that break entering `/advocates` after following a couple of links.

**Comment by marinaaisa** [comment]
These are the errors I'm facing reproducing this issue.
Are these ones the same you were facing, @delapuente ?
I'm gonna work on them.
<img width="553" alt="Captura de pantalla 2019-10-03 a las 11 07 40" src="https://user-images.githubusercontent.com/8567677/66114096-6e6a6180-e5ce-11e9-9e8d-6fa56c659973.png">
<img width="539" alt="Captura de pantalla 2019-10-03 a las 11 04 25" src="https://user-images.githubusercontent.com/8567677/66114101-70ccbb80-e5ce-11e9-9644-18b5ff0f37c6.png">

**Comment by delapuente** [comment]
Is it happening after changing between a couple of sections back and forth?

**Comment by marinaaisa** [comment]
Steps to reproduce:
1) Change `nuxt-link` instead of `a` at line: https://github.com/qiskit-community/community.qiskit.org/blob/master/components/menus/QiskitOrgMenu.vue#L20
2) Change `to` instead of `href` at line: https://github.com/qiskit-community/community.qiskit.org/blob/master/components/menus/QiskitOrgMenu.vue#L27
1) Change `nuxt-link` instead of `a` at line: https://github.com/qiskit-community/community.qiskit.org/blob/master/components/menus/QiskitOrgMenu.vue#L30
5) Move between routes `advocates`, `education` and `experiments` through the menu link.

**Comment by marinaaisa** [comment]
I figured out that the line https://github.com/qiskit-community/community.qiskit.org/blob/master/plugins/deep-load.ts#L49 is causing the error. But I still don't know why...
